services:
  server:
    image: drone/drone:2
    restart: on-failure
    ports:
    - '8002:80'
    - '9002:443'
    volumes:
    - /home/opc/docker/appdata/drone:/data
    environment:
    - DRONE_GITHUB_CLIENT_ID=secret
    - DRONE_GITHUB_CLIENT_SECRET=secret
    - DRONE_RPC_SECRET=secret
    - DRONE_SERVER_HOST=ip:port
    - DRONE_SERVER_PROTO=http
  runner:
    image: drone/drone-runner-docker:linux-arm64
    restart: on-failure
    ports:
    - '3000:3000'
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    environment:
    - DRONE_RUNNER_NAME=runner-1
    - DRONE_RUNNER_CAPACITY=2
    - DRONE_RPC_SECRET=secret
    - DRONE_RPC_HOST=ip:port
    - DRONE_RPC_PROTO=http
