services:
  rstudio:
    image: rocker/rstudio:latest
    restart: on-failure
    ports: 
    - '10001:8787'
    volumes:
    - data:/data
    environment:
      PASSWORD: passw0rd
volumes: 
  data:
