apiVersion: v1
kind: Namespace
metadata:
  name: jupyter
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter
  labels:
    app: jupyter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyter
  template:
    metadata:
      labels:
        app: jupyter
    spec:
      containers:
      - name: jupyter
        image: jupyter/minimal-notebook:latest
        ports:
        - containerPort: 8888
        env:
        - name: JUPYTER_ENABLE_LAB
          value: 'yes'
---
apiVersion: v1
kind: Service
metadata:
  name: jupyter
spec:
  selector:
    app: jupyter
  ports:
    - protocol: TCP
      port: 10001
      targetPort: 8888
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jupyter
spec:
  rules:
  - http:
      paths:
      - path: /jupyter
        backend:
          serviceName: jupyter
          servicePort: 10001
