apiVersion: v1
kind: Namespace
metadata:
  name: rstudio
---
apiVersion: v1
kind: Secret
metadata:
  name: rstudio
  namespace: rstudio
data:
  password: Mzk1MjgkdmRnN0pi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rstudio
  labels:
    app: rstudio
  namespace: rstudio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rstudio
  template:
    metadata:
      labels:
        app: rstudio
    spec:
      containers:
      - name: rstudio
        image: rocker/rstudio:latest
        ports:
        - containerPort: 8787
        env:
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: rstudio
              key: password
---
apiVersion: v1
kind: Service
metadata:
  name: rstudio-service
  namespace: rstudio
spec:
  selector:
    app: rstudio
  ports:
    - protocol: TCP
      port: 10002
      targetPort: 8787